# Generated by Django 4.2.11 on 2026-04-26 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(default='Extension token', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_domain', models.CharField(blank=True, max_length=255)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('spf', models.CharField(blank=True, max_length=50)),
                ('dkim', models.CharField(blank=True, max_length=50)),
                ('dmarc', models.CharField(blank=True, max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], default='safe', max_length=20)),
                ('raw_analysis', models.JSONField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analyzer.apitoken')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
