# Generated by Django 4.2.11 on 2026-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=64, unique=True)),
                ('subject', models.TextField(blank=True)),
                ('sender_email', models.CharField(blank=True, max_length=255)),
                ('local_risk_label', models.CharField(choices=[('mid', 'Mid'), ('high', 'High')], max_length=10)),
                ('raw_headers', models.TextField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
    ]
