# Generated by Django 4.2.11 on 2026-04-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_flaggedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='gmail_message_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
